### ISSUE TITLE
Kanban setup

### ISSUE THREAD

**Issue by shafiuyushawu** [shafiuyushawu/space-travelers#25]
# **Project requirement ✍️**

- Created an empty repository for the project with best practices of GitHub flow.
- Copied all project to-dos to the Kanban board.
- Assigned tasks to each member of the group 💯 .

## **Project description 🗒️**
- This group comprises two members, that is @shafiuyushawu and @ZewdieMc.
-  Please find the link to our project [space-travelers-kanban-board](https://github.com/shafiuyushawu/space-travelers/projects/1)

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @shafiuyushawu and @ZewdieMc,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You should provide the link to your Kanban board, not your repository.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by shafiuyushawu** [comment]
Hello @TedLivist 

Thank you!

**Comment by OyePriscilla** [comment]
Hi @shafiuyushawu  and @ZewdieMc 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Added link to GitHub project ✔️ 
Listed information about the number of people in the group ✔️ 
Assigned tasks to each member of the group fairly ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by shafiuyushawu** [comment]
@OyePriscilla Thank you!

**Comment by OyePriscilla** [comment]
> @OyePriscilla Thank you!

@shafiuyushawu You welcome!
